Platform: {
  Services: {
    API: {
      label: api-server
    }
  }
  Storage: {
    DB: {
      label: PostgreSQL
      apps: {
        class: table
        id: " "
        name: " "
      }
    }
  }
}

Client
