Platform: {
  Services: {
    API: {
      label: api-server
    }
  }
  Storage: {
    DB: {
      label: PostgreSQL
      users: {
        class: table
        id: " "
        email: " "
      }
    }
  }
}

Client
